# Workflow name
name: CI/CD

# Trigger workflow on push to main branch or pull requests to main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Test job: runs tests, linting, and build
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository code
    - uses: actions/checkout@v3

    # Setup Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    # Install project dependencies
    - name: Install dependencies
      run: npm ci

    # Run ESLint to check code quality
    - name: Run linter
      run: npm run lint

    # Run unit tests
    - name: Run tests
      run: npm test

    # Build the Next.js application
    - name: Build
      run: npm run build

  # Deploy job: deploys to Vercel if tests pass and we're on main branch
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    # Set environment variables from repository secrets
    env:
      NEXT_PUBLIC_DIGITRANSIT_API_URL: ${{ env.NEXT_PUBLIC_DIGITRANSIT_API_URL }}
      NEXT_PUBLIC_DIGITRANSIT_SUBSCRIPTION_KEY: ${{ secrets.NEXT_PUBLIC_DIGITRANSIT_SUBSCRIPTION_KEY }}

    steps:
    # Deploy to Vercel production environment
    - name: Deploying to Vercel production
      run: |
        echo "Installing Vercel CLI globally"
        npm install --global vercel
        echo "Pulling environment variables and project settings"
        vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        echo "Building the project"
        vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        echo "Deploying the built project to Vercel production environment"
        vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
